--- name:default
# The name of the imu frame.
imu_frame: imu
# name of the node in the scene file from which to get the imu data
name: imu
#name: passive

# The name of the world frame.
world_frame: imu_enu
--- name:crex

# name of the node in the scene file from which to get the imu data
name: "imu"

# name of the imu frame
imu_frame: "imu"

# name of the world frame
world_frame: "imu_nwu"
