--- name:default
# Minimum valid range of the laser range finder
name: "sensor_velodyne"
min_range: 1.0
max_range: 30.0
# Name of the RotatingRaySensor in the scene file
output_type: "pointcloud" #Select "depthmap" or "pointcloud" or "both"
--- name:crex
